Meeting 4 minutes
w3c/font-text-cg pull request #26
Opened 2020-10-19 19:02 UTC by simoncozens

2020-10-19 19:58 UTC, alerque requested changes
Thanks for being the scribe! Looks great.


If you don't mind I might do a little more cleanup, but since I'm getting distracted I figured I should post the bits I have to start with. I can commit these later when I come back to it too.

2020-10-19 19:58 UTC, alerque commented on minutes/meeting-202001019-4.md
> +Present
```suggestion
Present (IRC)
```

OR ditch this section, we probably don't need IRC vs. Video meeting attendees separately, a merged list or only the latter is probably good.

2020-10-19 19:58 UTC, alerque commented on minutes/meeting-202001019-4.md
> +* Chair: liang
```suggestion
* Chair: Liang Hai
```

Either use names or IRC nicks, not both side by side in the same section. Maybe names through the attendance section, nicks for transcript?

2020-10-19 19:58 UTC, alerque commented on minutes/meeting-202001019-4.md
> +Vladimir Levantovsky, Liang Hai, Simon Cozens, Andrew Glass, Anthrotype, Bobby de Vos, Caleb Maclennan, Chris Chapman, David Singer, dcorbett, Duncan MacMichael, John Hudson, Johnathan Kew, Laurence,
```suggestion
Vladimir Levantovsky, Liang Hai, Simon Cozens, Andrew Glass, Anthrotype, Bobby de Vos, Caleb Maclennan, Chris Chapman, David Singer, David Corbett, Duncan MacMichael, John Hudson, Johnathan Kew, Laurence, Mehmet Oğuz Derin, Nat McCully, Nate Willis, Ned Holbrook, Norbert, Renzhi Li, Simon Cozens, Toshiya Suzuki, Zachary Scheuren
```

We aren't afraid of Unicode are we?

2020-10-19 19:58 UTC, alerque commented on minutes/meeting-202001019-4.md
> +* Try setting up the github-bot
```suggestion
* Ask W3C for a dedicated video meeting space.
* Discuss meeting time scheduling on GitHub issue.
* Research setting up IRC/github-bot.
* @scottkellum, please post more notes from implementation responsive text prototypes.
```

2020-11-05 10:14 UTC, lianghai submitted a review, later dismissed
Additional improvements to the Attendance sections.

2020-11-05 10:14 UTC, lianghai commented on minutes/meeting-202001019-4.md
> +
```suggestion
```

Merge this attendance info in the IRC channel into the main section.

2020-11-05 10:14 UTC, lianghai commented on minutes/meeting-202001019-4.md
> +Vladimir Levantovsky, Liang Hai, Simon Cozens, Andrew Glass, Anthrotype, Bobby de Vos, Caleb Maclennan, Chris Chapman, David Singer, David Corbett, Duncan MacMichael, John Hudson, Johnathan Kew, Laur
```suggestion
Andrew Glass, Bobby de Vos, Caleb Maclennan\*, Chris Chapman\*, Cosimo Lupo\*, David Corbett\*, David Singer\*, Duncan MacMichael, Greg Hitchcock, John Hudson\*, Johnathan Kew\*, Laurence Penney\*, Liang Hai\*, Mehmet Oğuz Derin\*, Nat McCully\*, Nate Willis\*, Ned Holbrook\*, Norbert Lindenberg, Peter Constable\*, Renzhi Li, Scott Kellum\*, Simon Cozens\*, Toshiya Suzuki\*, Vladimir Levantovsky\*, Zachary Scheuren\*

\* Formal participants of the FTCG.

The IRC channel recorded the following nicks: liang, simon, Vlad, cjchapman, mehmetoguzderin, alerque, JohnHudson, dsinger, dscorbett, jfkthame, nmccully, Norbert
```

Changes:

- Added the following names according to my Zoom screenshots: Scott Kellum, Greg Hitchcock, Peter Constable
- Normalized the following names: Anthrotype → Cosimo Lupo, Laurence → Laurence Penney, Norbert → Lindenberg
- Removed a duplication of Simon’s name.
- Marked formal attendees.
- Applied a dumb alphabetical order.
- Incorporated the IRC attendance info.

2020-11-05 10:25 UTC, lianghai commented
Thank you guys, especially Simon… I couldn’t process this in time despite your great effort of taking all the notes…

Now I’m trying (some weird network issue is happening) to mark this PR as “non-substantive” at https://labs.w3.org/repo-manager/pr/id/w3c/font-text-cg/26 to pass the bot’s requirement for now. @simoncozens, you should [link your GitHub account with your W3C account](https://www.w3.org/users/myprofile/connectedaccounts) though, to prevent this from happening again.

2020-11-05 11:06 UTC, alerque submitted a review, later dismissed

2020-11-05 11:17 UTC, simoncozens commented
I've linked my accounts.

2020-11-05 11:17 UTC, lianghai commented on minutes/meeting-202001019-4.md
> +# Minutes of Meeting 4, 2020-10-17, 16:00–18:30 UTC
```suggestion
# Minutes of Meeting 4, 2020-10-19, 16:00–18:30 UTC
```

Corrected the date.

2020-11-05 11:29 UTC, alerque approved these changes

2020-11-05 11:45 UTC, merged